spring:
  datasource:
    url: ${DATABASE_URL}
    hikari:
      maximumPoolSize: 5

  kafka:
    bootstrap-servers: ${KAFKACLUSTER_BROKERS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKACLUSTER_USERNAME}"
        password="${KAFKACLUSTER_PASSWORD}";
    producer:
      transaction-id-prefix: ai-processing-tx-${DYNO:local}-
    consumer:
      concurrency: 1
    topics:
      incoming: ${KAFKACLUSTER_PREFIX}ai.processing.incoming
      outgoing: ${KAFKACLUSTER_PREFIX}ai.processing.outgoing
      processing-dlq: ${KAFKACLUSTER_PREFIX}ai.processing.processing.dlq

      groups-id:
        consumer: ${KAFKACLUSTER_PREFIX}ai-processing
        dlq: ${KAFKACLUSTER_PREFIX}ai-processing-dlq

  jpa:
    open-in-view: false
server:
  forward-headers-strategy: framework