spring:
  datasource:
    url: ${DATABASE_URL}
    hikari:
      maximumPoolSize: 5
  kafka:
    bootstrap-servers: ${KAFKACLUSTER_BROKERS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKACLUSTER_USERNAME}"
        password="${KAFKACLUSTER_PASSWORD}";
    consumer:
      auto-offset-reset: latest
      max-poll-records: 1
      fetch-max-wait: 500
      properties:
        "fetch.max.bytes": 1048576
        "max.partition.fetch.bytes": 1048576
        "receive.buffer.bytes": 65536
        "spring.json.trusted.packages": "*"
    listener:
      concurrency: 1
      type: single
  main:
    lazy-initialization: true

  jpa:
    open-in-view: false
server:
  forward-headers-strategy: framework