spring:
  datasource:
    url: ${DATABASE_URL}
    hikari:
      maximumPoolSize: 5
  kafka:
    bootstrap-servers: ${KAFKACLUSTER_BROKERS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      spring:
        kafka:
          bootstrap-servers: ${KAFKACLUSTER_BROKERS}
          properties:
            security.protocol: SASL_SSL
            sasl.mechanism: SCRAM-SHA-512
            "[sasl.jaas.config]": >
              org.apache.kafka.common.security.scram.ScramLoginModule required
              username="${KAFKACLUSTER_USERNAME}"
              password="${KAFKACLUSTER_PASSWORD}";
    consumer:
      auto-offset-reset: latest
      max-poll-records: 1
      isolation-level: read_uncommitted
      properties:
        spring.json.trusted.packages: "*"
        fetch.max.bytes: 1048576
        max.partition.fetch.bytes: 1048576
        receive.buffer.bytes: 65536
    producer:
      buffer-memory: 524288
      batch-size: 4096
      properties:
        max.in.flight.requests.per.connection: 1
        metadata.max.age.ms: 60000
    listener:
      concurrency: 1
      type: single
    topics:
      incoming: ${KAFKACLUSTER_PREFIX}ai.processing.raw
      outgoing: ${KAFKACLUSTER_PREFIX}ai.processing.filtered
      processing-dlq: ${KAFKACLUSTER_PREFIX}ai.processing.business.dlq
    groups-id:
      consumer: ${KAFKACLUSTER_PREFIX}ai-processing
      dlq: ${KAFKACLUSTER_PREFIX}ai-processing-dlq
    admin:
      auto-create: false
  main:
    lazy-initialization: true

  jpa:
    open-in-view: false
server:
  forward-headers-strategy: framework
logging:
  level:
    org.apache.kafka: DEBUG